# Generated by Django 4.2.27 on 2025-12-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_hash',
            field=models.CharField(db_index=True, editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_size',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
