# Generated by Django 4.2.27 on 2025-12-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_option_optiongroup_alter_category_slug_productclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclass',
            name='options',
            field=models.ManyToManyField(blank=True, to='catalog.option'),
        ),
    ]
